version: '2'
services:
    jhipsterscenarioo-app:
        image: jhipsterscenarioo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterscenarioo-mysql:3306/jhipsterscenarioo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterscenarioo-mysql:
        extends:
            file: mysql.yml
            service: jhipsterscenarioo-mysql
